(function() {
  var pgRequest = new XMLHttpRequest();
  var diffStamp = Date.now().toString() + Math.random().toString().substring(2);
  pgRequest.open('GET', '/pg_pixel?r=' + encodeURIComponent(document.referrer || '') + '&diff=' + diffStamp, true);
  pgRequest.send();
})()(function(){function a(){return"UnknownPageName"}function b(){return"unknown"}function c(){var a,b,c,d;return null!==(a=null===(b=navigator)||void 0===b||null===(c=b.serviceWorker)||void 0===c||null===(d=c.controller)||void 0===d?void 0:d.scriptURL)&&void 0!==a?a:"none"}window._bufferedErrors=[];const d=window.onerror;window.onerror=(a,b,c,e,f)=>{d&&d.call(window,a,b,c,e,f),window._bufferedErrors&&window._bufferedErrors.push([a,b,c,e,f])},window.addEventListener("load",()=>{if(!window._errorReportingInitialized){const d=window._bufferedErrors||[];window.fetch&&0!==d.length&&d.forEach(d=>{var e,f,g,h;const i=null===(e=d[4])||void 0===e||null===(f=e.constructor)||void 0===f?void 0:f.name,j=a();window.fetch("https://notify.bugsnag.com/",{body:JSON.stringify({apiKey:"e393bc25e52fe915ffb56c14ddf2ff1b",notifier:{name:"Airbnb UnhandledBufferedError Custom Fetch",version:"0.0.2",url:"https://www.airbnb.com/tracking/errors"},events:[{exceptions:[{errorClass:i||"Error",errorMessage:d[0],type:"browserjs",stacktrace:[{file:d[1]||"[unknown]",lineNumber:d[2]||0,columnNumber:d[3]||0}],message:d[0]}],severity:"error",unhandled:!0,device:{userAgent:null===(g=navigator)||void 0===g?void 0:g.userAgent,time:Date.now()},request:{clientIp:"[REDACTED]",url:null===(h=window.location)||void 0===h?void 0:h.href},breadcrumbs:[{type:"navigation",name:"Error Occurred",timestamp:Date.now(),metaData:{}}],context:j,groupingHash:(i||"BufferedError").concat("-",d[0]+"","-",j),metaData:{loop_name:"unknown-buffered-error",app_name:"unknown-buffered-error",service_worker_url:c(),error:{originalError:{name:"UnhandledBufferedError",message:"UnhandledBufferedError"}}},user:{id:b()}}]}),method:"POST"})})}})})();
// FID init code.
(function(a,b){function c(a){l.push(a),f()}function d(a,b){i||(i=b,j=a,k=new Date,f())}function e(){i&&(i=null,j=null,k=null)}function f(){0<=j&&j<k-n&&(l.forEach(a=>{a(j,i)}),l=[])}function g(c,e){function f(){d(c,e),h()}function g(){h()}function h(){b(o,f,m),b(p,g,m)}a(o,f,m),a(p,g,m)}function h(a){if(a.cancelable){const b=1e12<a.timeStamp,c=b?new Date:performance.now(),e=c-a.timeStamp;"pointerdown"===a.type?g(e,a):d(e,a)}}let i,j,k,l=[];const m={passive:!0,capture:!0},n=new Date,o="pointerup",p="pointercancel";(function(a){["click","mousedown","keydown","touchstart","pointerdown"].forEach(b=>{a(b,h,m)})})(a),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=c,self.perfMetrics.clearFirstInputDelay=e})(addEventListener,removeEventListener);
// TTFMP Polyfill code.
(function(a){function b(){const c=document.getElementById(i);h=0,c?g===c?e=a(b):"IMG"!==c.tagName||c.complete?a(function(){const a=performance.now();g=c,f?f(a):h=a,performance.measure&&performance.measure("TTFMP")}):e=a(b):e=a(b)}function c(a){h?a(h):f=a}function d(){cancelAnimationFrame(e)}let e,f,g,h;const i="FMP-target";e=a(b),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstMeaningfulPaint=c,self.perfMetrics.startSearchingForFirstMeaningfulPaint=function(){g=document.getElementById(i),b()},self.perfMetrics.stopSearchingForFirstMeaningfulPaint=d})(requestAnimationFrame);
// LCP Polyfill code
(function(a,b,c){function d(a,b,c){if(b>o*(1+q)||!document.body.contains(m)){var d;o=b,p=c,m=a,null===(d=x)||void 0===d?void 0:d(p,m,o)}}function e(a,b){if("IMG"!==a.tagName)b();else{const d=()=>c(b);a.complete?d():a.addEventListener("load",d,{once:!0})}}function f(a){var b;null===(b=w)||void 0===b?void 0:b.observe(a)}function g(a){return u.includes(a.tagName)||a.hasAttribute("data-lcp-candidate")}function h(){if(t)if(s)v||(v={IMG:document.getElementsByTagName("img"),H1:document.getElementsByTagName("h1"),H2:document.getElementsByTagName("h2"),H3:document.getElementsByTagName("h3"),H4:document.getElementsByTagName("h4"),H5:document.getElementsByTagName("h5"),SVG:document.getElementsByTagName("svg")}),u.forEach(a=>{Array.from(v[a]).forEach(a=>{f(a)})}),setTimeout(h,50);else{!r&&document.body&&(r=document.createNodeIterator(document.body,NodeFilter.SHOW_ELEMENT,a=>g(a)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT));for(let b;b=null===(a=r)||void 0===a?void 0:a.nextNode();){var a;f(b)}c(h)}}function i(){n=performance.now(),o=0,p=0,w=new IntersectionObserver(a=>{a.filter(a=>a.isIntersecting).forEach(a=>{const b=a.target,{width:c,height:f}=a.intersectionRect;e(b,()=>{const a=performance.now();d(b,c*f,a)})})}),c(h),y.forEach(b=>{a(b,j,z)})}function j(a){const b=a.target;"scroll"===a.type&&("expand-trigger"===(null===b||void 0===b?void 0:b.className)||"contract-trigger"===(null===b||void 0===b?void 0:b.className))||0===o||250>performance.now()-n||k()}function k(){var a;null===(a=w)||void 0===a?void 0:a.disconnect(),y.forEach(a=>{b(a,j,z)}),t=!1,w=null}function l(a){x=a,0!==p&&x(p,m,o)}let m,n=0,o=0,p=0;const q=666778e-9;let r,s=!1,t=!0;const u=["IMG","H1","H2","H3","H4","H5","SVG"];let v,w,x;const y=["click","mousedown","keydown","touchstart","pointerdown","scroll"],z={passive:!0,capture:!0};i(),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onLargestContentfulPaint=l,self.perfMetrics.startSearchingForLargestContentfulPaint=i.bind(null,!1),self.perfMetrics.stopSearchingForLargestContentfulPaint=k,self.perfMetrics.markIsHydratedForLargestContentfulPaint=()=>{s=!0},self.perfMetrics.registerLCPCandidate=f})(addEventListener,removeEventListener,requestAnimationFrame);
